spring:
  data:
    mongodb:
      uri: mongodb+srv://Ravi:Y2IBPD998sRgTPKU@sewa-sathi.mzqrpqh.mongodb.net/?retryWrites=true&w=majority&appName=Sewa-Sathi
      database: SewaSathi
      auto-index-creation: true